# Generated by Django 6.0.6 on 2026-07-02 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('apodo', models.CharField(blank=True, max_length=80)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='player_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(choices=[('7vs7', '7 vs 7'), ('8vs8', '8 vs 8'), ('9vs9', '9 vs 9'), ('10vs10', '10 vs 10'), ('11vs11', '11 vs 11')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('equipo1_color', models.CharField(choices=[('blanco', 'Blanco'), ('negro', 'Negro')], default='blanco', max_length=10)),
                ('equipo2_color', models.CharField(choices=[('blanco', 'Blanco'), ('negro', 'Negro')], default='negro', max_length=10)),
                ('jugadores', models.ManyToManyField(blank=True, to='mi_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='TeamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.IntegerField(choices=[(1, 'Equipo 1'), (2, 'Equipo 2')])),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='mi_app.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='TierEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('crack', 'Crack'), ('bueno', 'Bueno'), ('puede_ser_mejor', 'Puede ser mejor'), ('tronco', 'Tronco'), ('lesionado', 'Lesionado')], default='puede_ser_mejor', max_length=30)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.player')),
            ],
            options={
                'unique_together': {('player', 'match')},
            },
        ),
    ]
